/*
 * This source file was generated by the Gradle 'init' task
 */
package http.pg;

import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.nio.charset.StandardCharsets;

import com.google.gson.Gson;

public class Library {
    HttpClient client = HttpClient.newHttpClient();

    public boolean someLibraryMethod() {
        return true;
    }

    public String getEcho(String message) throws Exception {
        String uri = "https://postman-echo.com/get?message=" + URLEncoder.encode(message, StandardCharsets.UTF_8);
        HttpRequest request = HttpRequest.newBuilder(new URI(uri)).build();
        HttpResponse<String> response = client.send(request, BodyHandlers.ofString());
        if (response.statusCode() != 200) {
            throw new Exception(String.valueOf(response.statusCode()));
        }
        EchoResponseBody body = new Gson().fromJson(response.body(), EchoResponseBody.class);
        return body.getArgs().getMessage();
    }
}
