/*
 * This source file was generated by the Gradle 'init' task
 */
package http.pg;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void echoReturnsString() throws Exception {
        Library classUnderTest = new Library();
        String message = "Hello World";
        String result = classUnderTest.getEcho(message);
        assertEquals(result, message);
    }
}
